### PR TITLE
Remove timeout in test/app.js

### PR DESCRIPTION
**Pull request by gjeck**
Add withGenerators call to test since the app generator calls composeWith.
See http://yeoman.io/authoring/testing.html for further details. Super small
adjustment but I dig the project and want to help :)

### CODE REVIEW

**Comment by sondr3** [comment]
Hey, thanks for this pull request, everything looks good to me! I'll merge it locally and push it together with some other changes I have done in the background.

**Comment by gjeck** [comment]
No problem! Thank you for putting the project together. Sounds good on the
merge.

**Comment by sondr3** [comment]
Okay, pushed the fix alongside some minor others to the beta branch, this'll be automatically closed when I merge with master whenever that will be :smile:

**Comment by gjeck** [comment]
:+1: :smiley:

**Comment by sondr3** [comment]
Actually, now that I've merged it manually and moved the main page to the beta branch, all I'm going to do is write a bunch of documentation and then publish a beta on NPM. I'm going to close this pull request, thanks for figuring this out for me!

**Pull request closed without merging**
